obstacle_range: 3.0
raytrace_range: 3.5

#These values will need to be tweaked.  As for now they are test values. 
#footprint: [[0, 2.0], [2.0, 0], [0, -2.0], [-2.0, 0]]
#robot_radius: ir_of_robot
inflation_radius: 1.0
cost_scaling_factor: 3.0

observation_sources: point_cloud_sensor laser_scan_sensor

laser_scan_sensor: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: left_camera_optical_frame, data_type: PointCloud, topic: /ezrassor/front_camera/points2
, marking: true, clearing: true}
