obstacle_range: 2.5
raytrace_range: 3.0

#These values will need to be tweaked.  As for now they are test values. 
#footprint: [[0, 2.0], [2.0, 0], [0, -2.0], [-2.0, 0]]
#robot_radius: ir_of_robot
inflation_radius: 0.5

observation_sources: point_cloud_sensor #laser_scan_sensor

#laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: left_camera_optical_frame, data_type: PointCloud, topic: /ezrassor/front_camera/points2
, marking: true, clearing: true}
