frequency: 50

two_d_mode: true

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom

imu0: imu
imu0_config: [false, false, false,
              false,  false,  true,
              false, false, false,
              false,  false,  true,
              true,  false,  false]
imu0_nodelay: false
imu0_differential: false
imu0_relative: true
imu0_queue_size: 5
imu0_remove_gravitational_acceleration: true

odom0: diff_drive_controller/odom
odom0_config: [false, false, false,
              false,  false,  false,
              true, false, false,
              false,  false,  true,
              false,  false,  false]
odom0_nodelay: false
odom0_differential: false
odom0_relative: true
odom0_queue_size: 10
