ez_rassor:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_wheel_back_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: left_wheel_back_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_wheel_front_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: left_wheel_front_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_wheel_back_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: right_wheel_back_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}
  right_wheel_front_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: right_wheel_front_hinge
    pid: {p: 100.0, i: 0.01, d: 10.0}